### ISSUE TITLE
issueとpull requestのテンプレートの追加

### ISSUE THREAD

**Issue by Tiryoh** [rt-net/.github#3]
https://help.github.com/en/github/building-a-strong-community/about-issue-and-pull-request-templates

- [x] bug report
- [x] feature request
- [ ] question
- [x] 不具合報告
- [x] 改善要望
- [ ] 質問

**Comment by ShotaAk** [comment]
質問についてはテンプレートを作成しない。
GitHub新機能のDiscussionで代用する。
